// src/lib/ui/molecules/Contact.svelte
<script lang="ts">
  import { _ } from 'svelte-i18n'

  import type { Component } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  import { Section } from '$lib/enums'

  import Phone from '$lib/ui/icons/Phone.svelte'
  import UserA from '$lib/ui/icons/UserA.svelte'
  import UserB from '$lib/ui/icons/UserB.svelte'
  import ContactHero from '$lib/ui/icons/ContactHero.svelte'

  type Card = {
    name: string
    phone: string
    title: string
    description: string
    icon: Component
  }

  const cards: Card[] = [
    {
      icon: UserA,
      name: $_('component.contact.cards.0.name'),
      title: $_('component.contact.cards.0.title'),
      description: $_('component.contact.cards.0.description'),
      phone: $_('component.contact.cards.0.phone'),
    },
    {
      icon: UserB,
      name: $_('component.contact.cards.1.name'),
      title: $_('component.contact.cards.1.title'),
      description: $_('component.contact.cards.1.description'),
      phone: $_('component.contact.cards.1.phone'),
    },
  ]

  const { class: className, ...props }: HTMLAttributes<HTMLElement> = $props()
</script>

{#snippet card(props: Card)}
  <a
    href={`tel:+42${props.phone.replaceAll(' ', '')}`}
    class="rounded-2xl bg-gradient-to-b from-gray-200 to-gray-100 p-px shadow-xl dark:from-gray-700/60 dark:to-gray-800/40 dark:shadow-black/30"
  >
    <div class="flex items-center gap-5 rounded-[calc(1rem-1px)] bg-white p-6 sm:p-8 dark:bg-gray-900">
      <div class="shrink-0 self-start rounded-2xl bg-gray-800 p-2 text-white">
        <props.icon class="h-17 w-auto" />
      </div>

      <div class="flex min-w-0 flex-col gap-1 text-gray-900 dark:text-white">
        <h3 class="text-xl font-bold">{props.name}</h3>

        <p class="text-primary mt-1 text-xs font-medium tracking-widest uppercase">{props.title}</p>

        <p class="mt-3 text-sm tracking-tight text-gray-500 dark:text-gray-400">{props.description}</p>

        <span
          class="text-md mt-3 inline-flex items-center gap-2 font-medium text-gray-700 transition-colors hover:text-gray-900 dark:text-gray-300 dark:hover:text-white"
        >
          <Phone class="h-[1.33em] w-auto shrink-0" />

          {props.phone}
        </span>
      </div>
    </div>
  </a>
{/snippet}

<section class={['overflow-x-hidden bg-gray-900 text-white dark:bg-gray-950', className]} {...props}>
  <div class="pt-20 pb-40">
    <div class="contained">
      <div class="flex flex-col items-center justify-between lg:flex-row">
        <div class="max-w-lg text-center lg:text-left">
          <h2 class="mb-4 text-4xl font-bold">
            {$_('component.contact.title')}
          </h2>

          <p class="text-gray-400">{$_('component.contact.description')}</p>
        </div>

        <ContactHero class="mt-10 h-64 w-auto opacity-90 sm:h-80 lg:mt-0" />
      </div>
    </div>
  </div>

  <div id={Section.CONTACT} class="contained -mt-42 grid gap-4 pt-18 sm:gap-6 md:grid-cols-2 lg:-mt-41 lg:pt-17">
    {#each cards as item}
      {@render card(item)}
    {/each}
  </div>
</section>

// src/components/contact.tsx
import type { FunctionComponent, HTMLAttributes } from 'preact'

import { Section } from '~/enums/mod.ts'

import Phone from '~/icons/phone.tsx'
import UserA from '~/icons/user-a.tsx'
import UserB from '~/icons/user-b.tsx'
import ContactHero from '~/icons/contact-hero.tsx'

type T = Record<'title' | 'description', string>

type CardData = Record<'name' | 'phone' | 'title' | 'description', string>

type Props = {
  t: T
  cards: CardData[]
} & HTMLAttributes<HTMLElement>

const Card: FunctionComponent<CardData & { index: number }> = ({ name, title, description, phone, index }) => (
  <a
    href={`tel:+42${phone.replaceAll(' ', '')}`}
    class='p-px rounded-2xl bg-gradient-to-b from-gray-200 to-gray-100 dark:from-gray-700/60 dark:to-gray-800/40 shadow-xl dark:shadow-black/30'
  >
    <div class='flex items-center gap-5 rounded-[calc(1rem-1px)] bg-white dark:bg-gray-900 p-6 sm:p-8'>
      <div class='shrink-0 rounded-2xl bg-gray-800 p-2 text-white self-start'>
        {index % 2 ? <UserB class='h-17 w-auto' /> : <UserA class='h-17 w-auto' />}
      </div>

      <div class='flex flex-col gap-1 min-w-0 text-gray-900 dark:text-white'>
        <h3 class='text-xl font-bold'>{name}</h3>

        <p class='mt-1 text-xs font-medium uppercase tracking-widest text-primary'>{title}</p>

        <p class='mt-3 text-sm text-gray-500 dark:text-gray-400 tracking-tight'>{description}</p>

        <span class='mt-3 inline-flex items-center gap-2 text-md font-medium text-gray-700 transition-colors hover:text-gray-900 dark:text-gray-300 dark:hover:text-white'>
          <Phone class='h-[1.33em] w-auto shrink-0' />

          {phone}
        </span>
      </div>
    </div>
  </a>
)

export default ({ t, cards, class: className = '', ...props }: Props) => (
  <section class={`overflow-x-hidden bg-gray-900 dark:bg-gray-950 text-white ${className}`} {...props}>
    <div class='pb-40 pt-20'>
      <div class='contained'>
        <div class='flex flex-col items-center justify-between lg:flex-row'>
          <div class='max-w-lg text-center lg:text-left'>
            <h2 class='mb-4 text-4xl font-bold'>
              {t.title}
            </h2>

            <p class='text-gray-400'>{t.description}</p>
          </div>

          <ContactHero class='mt-10 h-64 w-auto opacity-90 sm:h-80 lg:mt-0' />
        </div>
      </div>
    </div>

    <div id={Section.CONTACT} class='contained pt-18 lg:pt-17 -mt-42 lg:-mt-41 grid gap-4 sm:gap-6 md:grid-cols-2'>
      {cards.map((card, index) => <Card key={index} index={index} {...card} />)}
    </div>
  </section>
)
