// src/lib/ui/molecules/Header.svelte
<script lang="ts">
  import { _ } from 'svelte-i18n'

  import type { HTMLAttributes } from 'svelte/elements'

  import { scroll } from '$lib/composables/scroll'

  import { Section } from '$lib/enums'

  import Link from '$lib/ui/atoms/Link.svelte'
  import IconButton from '$lib/ui/atoms/IconButton.svelte'

  import X from '$lib/ui/icons/X.svelte'
  import Sun from '$lib/ui/icons/Sun.svelte'
  import Moon from '$lib/ui/icons/Moon.svelte'
  import Burger from '$lib/ui/icons/Burger.svelte'
  import LogoLarge from '$lib/ui/icons/LogoLarge.svelte'
  import LogoSmall from '$lib/ui/icons/LogoSmall.svelte'

  type LinkProps = {
    href: string
    label: string
  }

  const links: LinkProps[] = [
    { href: `#${Section.CONTACT}`, label: $_('generic.contact') },
    { href: `#${Section.OFFERINGS}`, label: $_('generic.offerings') },
  ]

  const { class: className, ...props }: HTMLAttributes<HTMLElement> = $props()

  let dropdown: HTMLDivElement
  let backdrop: HTMLDivElement

  const scrolled = $derived<boolean>($scroll > 0.01)

  const toggleDropdown = () => {
    dropdown.classList.toggle('scale-y-0')
    backdrop.classList.toggle('scale-y-100')
  }

  const toggleDarkMode = () => {
    const isDark = document.documentElement.classList.toggle('dark')

    localStorage.setItem('theme', isDark ? 'dark' : 'white')
  }
</script>

{#snippet logo()}
  <Link href="/" class="inline-flex gap-2 sm:gap-3 lg:gap-4" aria-label={$_('generic.brand')}>
    <LogoSmall class="h-7 w-auto sm:h-8 lg:h-9" />
    <LogoLarge class="h-7 w-auto sm:h-8 lg:h-9" />
  </Link>
{/snippet}

{#snippet linkList(onClick?: () => void)}
  {#each links as { href, label }}
    <Link {href} class="text-sm capitalize" onclick={onClick}>
      {label}
    </Link>
  {/each}

  <IconButton aria-label={$_('component.header.toggleTheme')} onclick={toggleDarkMode}>
    <Sun class="hidden h-5 w-5 text-white duration-300 hover:rotate-180 dark:inline-block" />
    <Moon class="h-4 w-4 text-gray-700 duration-500 hover:rotate-[360deg] dark:hidden" />
  </IconButton>
{/snippet}

<header
  class={[
    'fixed z-40 w-full transition-colors duration-300',
    className,
    { 'bg-white/70 backdrop-blur-md dark:bg-gray-900/70': scrolled },
  ]}
  {...props}
>
  <nav
    class={[
      'relative contained flex items-center justify-between transition-[padding] duration-300',
      scrolled ? 'py-4' : 'py-6',
    ]}
  >
    {@render logo()}

    <div class="-mr-2 flex items-center lg:hidden">
      <IconButton aria-label={$_('component.header.openMenu')} onclick={toggleDropdown}>
        <Burger class="mx-[3px] my-[5px] h-3.5 w-4.5" />
      </IconButton>

      <div
        bind:this={dropdown}
        class="fixed inset-0 z-10 h-screen w-full origin-top scale-y-0 bg-white/70 backdrop-blur-2xl transition duration-500 lg:hidden dark:bg-gray-900/70"
      ></div>

      <div bind:this={backdrop} class="absolute inset-x-0 top-0 z-10 origin-top-right scale-y-0 transform p-4 transition">
        <div
          class="overflow-hidden rounded-xl border border-gray-100 bg-white shadow-md shadow-gray-200/50 dark:border-gray-800 dark:bg-gray-900 dark:shadow-none"
        >
          <div class="flex items-center justify-between px-5 pt-4">
            {@render logo()}

            <IconButton aria-label={$_('component.header.closeMenu')} class="-mr-2" onclick={toggleDropdown}>
              <X class="h-5 w-5" />
            </IconButton>
          </div>

          <div class="flex flex-col items-start space-y-4 px-5 pt-4 pb-3">
            {@render linkList(toggleDropdown)}
          </div>
        </div>
      </div>
    </div>

    <div class="hidden items-center gap-x-8 lg:flex">
      {@render linkList()}
    </div>
  </nav>
</header>

// src/islands/header.tsx
import { computed } from '@preact/signals'
import { createRef, type FunctionComponent, type HTMLAttributes } from 'preact'

import { scroll } from '~/composables/scroll.ts'

import Link from '~/components/link.tsx'
import IconButton from '~/components/icon-button.tsx'

import X from '~/icons/x.tsx'
import Sun from '~/icons/sun.tsx'
import Moon from '~/icons/moon.tsx'
import Burger from '~/icons/burger.tsx'
import LogoLarge from '~/icons/logo-large.tsx'
import LogoSmall from '~/icons/logo-small.tsx'

import { Section } from '~/enums/mod.ts'

type T = Record<'offerings' | 'contact', string>

type LinkProps = {
  href: string
  label: string
}

type Props = { t: T } & HTMLAttributes<HTMLElement>

const toggleDarkMode = () => {
  const isDark = document.documentElement.classList.toggle('dark')

  localStorage.setItem('theme', isDark ? 'dark' : 'white')
}

const Logo = () => (
  <Link href='/' class='inline-flex gap-2 sm:gap-3 lg:gap-4'>
    <LogoSmall class='w-auto h-7 sm:h-8 lg:h-9' />
    <LogoLarge class='w-auto h-7 sm:h-8 lg:h-9' />
  </Link>
)

export default ({ t, class: className = '', ...props }: Props) => {
  const dropdown = createRef<HTMLDivElement>()
  const backdrop = createRef<HTMLDivElement>()

  const scrolled = computed<boolean>(() => scroll.value > 0.01)
  const headerBlur = computed<string>(() => scrolled.value ? 'bg-white/70 dark:bg-gray-900/70 backdrop-blur-md' : '')

  const links: LinkProps[] = [
    { href: `#${Section.CONTACT}`, label: t.contact },
    { href: `#${Section.OFFERINGS}`, label: t.offerings },
  ]

  const toggleDropdown = () => {
    dropdown.current?.classList.toggle('scale-y-0')
    backdrop.current?.classList.toggle('scale-y-100')
  }

  const Links: FunctionComponent<{ onClick?: () => void }> = ({ onClick }) => (
    <>
      {links.map(({ href, label }, index) => <Link class='text-sm capitalize' href={href} key={index} onClick={onClick}>{label}</Link>)}

      <IconButton onClick={toggleDarkMode}>
        <Sun class='w-5 h-5 text-white duration-300 hidden dark:inline-block hover:rotate-180' />
        <Moon class='w-4 h-4 text-gray-700 duration-500 dark:hidden hover:rotate-[360deg]' />
      </IconButton>
    </>
  )

  return (
    <header {...props} class={`fixed z-40 w-full transition-colors duration-300 ${className} ${headerBlur}`}>
      <nav class={`contained relative flex items-center justify-between transition-[padding] duration-300 ${scrolled.value ? 'py-4' : 'py-6'}`}>
        <Logo />

        <div class='flex items-center -mr-2 lg:hidden'>
          <IconButton onClick={toggleDropdown}>
            <Burger class='w-4.5 h-3.5 mx-[3px] my-[5px]' />
          </IconButton>

          <div
            ref={backdrop}
            class='scale-y-0 fixed inset-0 z-10 w-full h-screen transition duration-500 origin-top bg-white/70 backdrop-blur-2xl dark:bg-gray-900/70 lg:hidden'
          />

          <div ref={dropdown} class='absolute inset-x-0 top-0 z-10 p-4 transition origin-top-right transform scale-y-0'>
            <div class='overflow-hidden bg-white border border-gray-100 shadow-md shadow-gray-200/50 dark:shadow-none dark:border-gray-800 rounded-xl dark:bg-gray-900'>
              <div class='flex items-center justify-between px-5 pt-4'>
                <Logo />

                <IconButton class='-mr-2' onClick={toggleDropdown}>
                  <X class='w-5 h-5' />
                </IconButton>
              </div>

              <div class='flex flex-col items-start px-5 pt-4 pb-3 space-y-4'>
                <Links onClick={toggleDropdown} />
              </div>
            </div>
          </div>
        </div>

        <div class='hidden items-center gap-x-8 lg:flex'>
          <Links />
        </div>
      </nav>
    </header>
  )
}
